---
driver:
  name: vagrant

provisioner:
  name: nodes
  client_rb: {
    client_key: "/tmp/kitchen/clients/hdfs-nn-ubuntu-1404.pem"
  }

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
      - 'recipe[java::oracle]'
      - 'recipe[bcpc-hadoop::hdp_repo]'
    attributes: {
      java: {
        jdk_version: 8,
        jdk: {
          "8": {
            x86_64: {
              url: "http://10.0.2.2:9090/jdk-8u65-linux-x64.tar.gz",
              checksum: "88db2aacdc222c2add4d92822f528b7a2101552272db4487f33b38b0b47826e7"
            }
          }
        },
        oracle: {
          accept_oracle_download_terms: true
        }
      },
      bcpc: {
        management: {
          cidr: "172.28.128.0/24",
          gateway: "172.28.128.1",
          interface: "eth1"
        },
        floating: {
          cidr: "172.28.128.0/24",
          gateway: "172.28.128.1",
          interface: "eth1"
        },
        storage: {
          cidr: "172.28.128.0/24",
          gateway: "172.28.128.1",
          interface: "eth1"
        },
        hadoop: {
          repos: {
            hortonworks: 'http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.3.2.0/',
            hdp_utils: 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/ubuntu14'
          },
          cluster-name: "test-kitchen",
          mounts: [0],
          hdfs: {
            dfs_replication_factor: 1
          }
        }
      }
    }
suites:
  - name: mysql_connector
    run_list:
      - 'recipe[bcpc::mysql_connector]' 
      - 'recipe[bcpc::test_mysql_connector]' 
    attributes:
      bcpc:
        bin_dir:
          path: "/tmp/"
  - name: kafka-zookeeper
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
    run_list:
      - 'recipe[kafka-bcpc::zookeeper_server]'
  - name: kafka-server
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
      kafka: {
        version: '0.8.2.1',
        scala_version: '2.9.2',
        checksum: '',
        md5_checksum: ''
      }
    }
    run_list:
      - 'recipe[kafka-bcpc::default]' 
      - 'recipe[kafka-bcpc::setattr]'
      - 'recipe[kafka::default]'
      - 'recipe[kafka-bcpc::kafka]'
  - name: hadoop-zookeeper
    driver:
      network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::default]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::zookeeper_server]'
  - name: hdfs-nn
    driver:
      customize:
        memory: 1024
        cpus: 2
      network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::default]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::namenode_no_HA]'
  - name: hdfs-rm
    driver:
      customize:
        memory: 1024
      network:
        - "'private_network', { type: 'dhcp' }"
    attributes: {
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::default]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::resoucemanager]'
  - name: hdfs-dn
    driver:
      customize:
        memory: 1024
      network:
        - "'private_network', { type: 'dhcp' }"
    attributes: {
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::default]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::datanode]'
