---
driver:
  name: vagrant

provisioner:
  name: nodes

platforms:
  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
      - 'recipe[java::oracle]'
      - 'recipe[bcpc-hadoop::hdp_repo]'
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true
        }
      },
      bcpc: {
        hadoop: {
          repos: {
            hortonworks: 'http://public-repo-1.hortonworks.com/HDP/ubuntu14/2.x/updates/2.3.2.0/',
            hdp_utils: 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/ubuntu14'
          }
        }
      }
    }
suites:
  - name: mysql_connector
    run_list:
      - 'recipe[bcpc::mysql_connector]' 
      - 'recipe[bcpc::test_mysql_connector]' 
    attributes:
      bcpc:
        bin_dir:
          path: "/tmp/"
  - name: zookeeper
    driver:
      customize:
        network:
        - ["private_network", { type: "dhcp" }]
    run_list:
      - 'recipe[kafka-bcpc::zookeeper_server]'
  - name: kafka
    driver:
      customize:
        network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
      kafka: {
        version: '0.8.2.1',
        scala_version: '2.9.2',
        checksum: '',
        md5_checksum: ''
      }
    }
    run_list:
      - 'recipe[kafka-bcpc::default]' 
      - 'recipe[kafka-bcpc::setattr]'
      - 'recipe[kafka::default]'
      - 'recipe[kafka-bcpc::kafka]'
  - name: hdfs-nn
    driver:
      customize:
        memory: 1024
        cpus: 2
        network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true,
        }
      },
      bcpc: {
        hadoop: {
          cluster-name: "test-kitchen",
          mounts: [0],
          hdfs: {
            dfs_replication_factor: 1
          }
        }
      }
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::namenode_no_HA]'
  - name: hdfs-rm
    driver:
      customize:
        memory: 1024
        network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
      bcpc: {
        hadoop: {
          cluster-name: "test-kitchen",
          mounts: [0],
          hdfs: {
            dfs_replication_factor: 1
          }
        }
      }
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::resoucemanager]'
  - name: hdfs-dn
    driver:
      customize:
        memory: 1024
        network:
        - ["private_network", { type: "dhcp" }]
    attributes: {
      java: {
        ark_download_timeout: 1800,
        ark_timeout: 1800
      },
      bcpc: {
        hadoop: {
          cluster-name: "test-kitchen",
          mounts: [0],
          hdfs: {
            dfs_replication_factor: 1
          }
        }
      }
    }
    run_list:
      - 'recipe[bcpc::chef_vault_install]'
      - 'recipe[bcpc::networking]'
      - 'recipe[bcpc-hadoop::configs]'
      - 'recipe[bcpc-hadoop::hadoop_config]'
      - 'recipe[bcpc-hadoop::datanode]'
