source 'https://supermarket.chef.io'

cookbook 'dpkg_autostart', git: 'https://github.com/hw-cookbooks/dpkg_autostart.git'
cookbook 'cobblerd', git: 'https://github.com/bloomberg/cobbler-cookbook.git'
metadata
